Repository ag-students/support-service, pull requests merged in 2021-07, with the labels that each got.

#7 Resolves #2, resolves #3; Repository setup & configuration through viper
  .gitignore
  Makefile
  cmd/communication/main.go
  config/config.go
  config/config.yaml
  docker-compose.yml
  docker/communication.Dockerfile.dev
  internal/microservices/communication/models/communication.go
  internal/microservices/communication/repository/postgres/communication_psql.go
  internal/microservices/communication/repository/postgres/postgres.go
  internal/microservices/communication/repository/repository.go
  internal/microservices/communication/services/communicate.go
Labels: enhancement

#12 Feature/ci setup
  .env
  .github/workflows/actions-config.yaml
  .gitignore
  Makefile
  cmd/goose/main.go
  db/migrations/20210707073105_init.sql
  go.mod
  go.sum
  internal/microservices/communication/repository/postgres/communication_psql_test.go
  internal/microservices/communication/services/communicate.go
Labels: WIP

#17 Added docsgenerator to container
  Makefile
  docker-compose.yml
  docker/communication.Dockerfile.dev
  docker/docsgenerator.Dockerfile.dev
Labels: enhancement

#19 added function to generate pdf file
  .gitignore
  cmd/docsgenerator/createPDF.go
  cmd/docsgenerator/font/cp1251.map
  cmd/docsgenerator/font/helvetica_1251.json
  cmd/docsgenerator/font/helvetica_1251.z
  cmd/docsgenerator/main.go
  cmd/docsgenerator/passport.png
  go.mod
  go.sum
Labels: enhancement

#23 compose fixed
  .gitignore
  Makefile
  docker-compose.yml
Labels: bug

#24 Добавление локального серверного хранилища с помощью сервиса minIO
  .env
  .gitignore
  Makefile
  cmd/communication/main.go
  cmd/docsgenerator/main.go
  docker-compose.yml
  go.mod
  go.sum
  internal/microservices/communication/delivery/mq/kafka.go
  internal/microservices/communication/delivery/mq/kafka_sms_consumer.go
  internal/microservices/communication/models/communication.go
  internal/microservices/communication/models/message.go
  internal/microservices/communication/repository/postgres/communication_psql.go
  internal/microservices/communication/repository/postgres/communication_psql_test.go
  internal/microservices/communication/repository/postgres/postgres.go
  internal/microservices/communication/services/message_bird.go
  internal/microservices/docsgenerator/services/minio-interaction.go
  nginx.conf
  pkg/pdf-creator/createPDF.go
Labels: WIP
